import Head from "next/head";
import Navbar from "../components/Global/Navbar";
import ContactUs from "../components/Home/ContactUs";
import Experience from "../components/Home/Experience";
import Hero from "../components/Home/Hero";
import How from "../components/Home/How";
import Projects from "../components/Home/Projects";
import Testimonials from "../components/Home/Testimonials";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Humna Butt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Experience />
      <How />
      <Projects />
      <div class="overflow-hidden">
        <Testimonials />
        <ContactUs />
      </div>
    </main>
  );
}
